[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
Cross-Origin-Opener-Policy = "same-origin-allow-popups"
Content-Security-Policy = "frame-src https://backoffice.modality.one/login/google/iframe;"

[[redirects]]
from = "/login/google/iframe"
to = "https://localhost/login/google/iframe"
status = 200
force = true

from = "/login/google/callback"
to = "https://localhost/login/google/callback"
status = 200
force = true
