[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
Cross-Origin-Opener-Policy = "same-origin-allow-popups"
Content-Security-Policy = "frame-src https://backoffice.modality.one/login/google;"

[[redirects]]
from = "/login/google"
to = "https://young-earwig-80.telebit.io/login/google"
status = 200
force = true

[[redirects]]
from = "/login/google/callback"
to = "https://young-earwig-80.telebit.io/login/google/callback"
status = 200
force = true
